Website = "https://github.com/leessmin/kde_gemini"

[Details]
  Icon = "resource/logo.png"
  Name = "kde_gemini"
  ID = "com.leessmin.kde_gemini"
  Version = "0.3.0"
  Build = 10

[LinuxAndBSD]
  GenericName = "Application"
  Categories = ["Utility"]
  Comment = "Automatically switch between KDE plasma desktop themes"
  Keywords = ["night", "dark", "day", "bright", "color", "theme", "kde"]
